/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TegeAdminRouteImport } from './routes/tege.admin'
import { Route as ApiCronBotJobsRouteImport } from './routes/api/cron/bot-jobs'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TegeAdminRoute = TegeAdminRouteImport.update({
  id: '/tege/admin',
  path: '/tege/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronBotJobsRoute = ApiCronBotJobsRouteImport.update({
  id: '/api/cron/bot-jobs',
  path: '/api/cron/bot-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tege/admin': typeof TegeAdminRoute
  '/api/cron/bot-jobs': typeof ApiCronBotJobsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tege/admin': typeof TegeAdminRoute
  '/api/cron/bot-jobs': typeof ApiCronBotJobsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tege/admin': typeof TegeAdminRoute
  '/api/cron/bot-jobs': typeof ApiCronBotJobsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tege/admin'
    | '/api/cron/bot-jobs'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tege/admin'
    | '/api/cron/bot-jobs'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/tege/admin'
    | '/api/cron/bot-jobs'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TegeAdminRoute: typeof TegeAdminRoute
  ApiCronBotJobsRoute: typeof ApiCronBotJobsRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tege/admin': {
      id: '/tege/admin'
      path: '/tege/admin'
      fullPath: '/tege/admin'
      preLoaderRoute: typeof TegeAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/bot-jobs': {
      id: '/api/cron/bot-jobs'
      path: '/api/cron/bot-jobs'
      fullPath: '/api/cron/bot-jobs'
      preLoaderRoute: typeof ApiCronBotJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TegeAdminRoute: TegeAdminRoute,
  ApiCronBotJobsRoute: ApiCronBotJobsRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
