
REVOKE EXECUTE ON FUNCTION public.finish_game(NUMERIC, INTEGER[], JSONB, BIGINT, INTEGER, NUMERIC) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.finish_game(NUMERIC, INTEGER[], JSONB, BIGINT, INTEGER, NUMERIC) TO service_role;
